// try & catch
// the try statements allows you to define a block of code to be tested for errors while it is being executed

// the catch allows you to define a block of code to be executed , if an error occurs in the try block 


// try{
//     console.log(a);
    
// }catch(error){
//     console.log('caught an error a is not defined');
//     console.log(error);
    
// }


// Arrow Functions


// const sum = (a,b) =>{
//     console.log(a+b);
    
// }